# Generated by Django 4.1.4 on 2023-01-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Coder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
    ]
