# Generated by Django 4.1.4 on 2023-01-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Coder', '0003_alter_entregable_fecha_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='fecha_entrega',
        ),
    ]
